In [195]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, make_scorer
from sklearn.model_selection import cross_val_score, GridSearchCV, StratifiedKFold, train_test_split



In [196]:
#lectura de datos
archivo=pd.read_csv('/content/drive/MyDrive/cuartapregunta2doparcial/audit_risk.csv')
archivo.head()

Sector_score LOCATION_ID  PARA_A  ...  Detection_Risk  Audit_Risk  Risk
0          3.89          23    4.18  ...             0.5      1.7148     1
1          3.89           6    0.00  ...             0.5      0.5108     0
2          3.89           6    0.51  ...             0.5      0.3096     0
3          3.89           6    0.00  ...             0.5      3.5060     1
4          3.89           6    0.00  ...             0.5      0.2832     0

[5 rows x 27 columns]

In [197]:
#muestra los estadisticos mas significativos del dataset
archivo.describe()

Sector_score      PARA_A  ...  Audit_Risk        Risk
count    776.000000  776.000000  ...  776.000000  776.000000
mean      20.184536    2.450194  ...    7.168158    0.393041
std       24.319017    5.678870  ...   38.667494    0.488741
min        1.850000    0.000000  ...    0.280000    0.000000
25%        2.370000    0.210000  ...    0.316700    0.000000
50%        3.890000    0.875000  ...    0.555600    0.000000
75%       55.570000    2.480000  ...    3.249900    1.000000
max       59.850000   85.000000  ...  961.514400    1.000000

[8 rows x 26 columns]

In [198]:
# filas y columnas
archivo.shape

(776, 27)

In [199]:
#elimnana datos albitrarios y los remeplazamos con la media
archivo = archivo.replace("?", np.NaN)
archivo = archivo.fillna(archivo.mean())

for column in archivo.columns:
    if archivo[column].dtypes == 'object':
        archivo[column] = archivo[column].fillna(archivo[column].value_counts().index[0])

In [200]:
#convertir los valores no numericos en valores numericos
le = LabelEncoder()

for column in archivo.columns:
    if archivo[column].dtype=='object':
        archivo[column]=le.fit_transform(archivo[column])

archivo


Sector_score  LOCATION_ID  PARA_A  ...  Detection_Risk  Audit_Risk  Risk
0            3.89           14    4.18  ...             0.5      1.7148     1
1            3.89           38    0.00  ...             0.5      0.5108     0
2            3.89           38    0.51  ...             0.5      0.3096     0
3            3.89           38    0.00  ...             0.5      3.5060     1
4            3.89           38    0.00  ...             0.5      0.2832     0
..            ...          ...     ...  ...             ...         ...   ...
771         55.57           41    0.49  ...             0.5      0.3156     0
772         55.57            6    0.47  ...             0.5      0.3136     0
773         55.57            4    0.24  ...             0.5      0.2912     0
774         55.57            8    0.20  ...             0.5      0.2880     0
775         55.57            5    0.00  ...             0.5      0.2928     0

[776 rows x 27 columns]

In [201]:
archivo=archivo.values
X,y=archivo[:,0:26], archivo[:,26]
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(X)
print(X)
print(y)

[[ 3.89   14.      4.18   ...  0.4     0.5     1.7148]
 [ 3.89   38.      0.     ...  0.4     0.5     0.5108]
 [ 3.89   38.      0.51   ...  0.4     0.5     0.3096]
 ...
 [55.57    4.      0.24   ...  0.4     0.5     0.2912]
 [55.57    8.      0.2    ...  0.4     0.5     0.288 ]
 [55.57    5.      0.     ...  0.4     0.5     0.2928]]
[1. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0.
 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0.
 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0.
 1. 1. 

In [202]:
#dividir los datos en datos de entrenamineto y datos de testeo 
X_train, X_test, y_train, y_test = train_test_split(rescaledX, y, test_size=0.20, random_state=0)

In [203]:
#trabajr con un red neuronal
clasificador=MLPClassifier(hidden_layer_sizes=(100,200,40), solver='adam', random_state=1, max_iter=200, activation='relu')
#entrenamiento
clasificador.fit(X_train, y_train)
#prediccion
prediccion=clasificador.predict(X_test)
print(prediccion)


[1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0.
 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1.
 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1.
 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 1.
 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0.
 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0.]


In [204]:
#matriz de confusion mediante sklearn.metrics
print("matriz de confusion\n ",confusion_matrix(y_test, prediccion))



matriz de confusion
  [[101   0]
 [  2  53]]
